#!/bin/bash

g++ -std=c++14 \
	-m32 \
	-fPIC \
	-static-libstdc++ \
	-Isrc/SourceAutoRecord/ \
	-Isrc/SourceAutoRecord/Features/ \
	-Ilibs/ \
	-o sar.so src/SourceAutoRecord/Main.cpp \
	-shared \
	-Wall

cp -fu "sar.so" "/home/nekz/.local/share/Steam/steamapps/common/Portal 2/sar.so"
#cp -fu "sar.so" "/home/nekz/.local/share/Steam/steamapps/common/Half-Life 2/hl2/sar.so"
#cp -fu "sar.so" "/home/nekz/.local/share/Steam/steamapps/common/The Stanley Parable/sar.so"
#cp -fu "sar.so" "/home/nekz/.local/share/Steam/steamapps/common/The Beginners Guide/sar.so"